"""Quality report data models.

This module defines models for the quality report generated by QualityReporter.
"""

from pydantic import BaseModel, Field


class StageQualitySummary(BaseModel):
    """Quality summary for a single pipeline stage.

    Attributes:
        stage_name: Name of the stage (capture, preprocess, reconstruct, optimize)
        status: Quality status (pass, warn, fail, pending)
        reasons: List of reasons for the status
    """

    stage_name: str
    status: str  # "pass", "warn", "fail", "pending"
    reasons: list[str] = Field(default_factory=list)

    model_config = {"frozen": True}


class QualityReport(BaseModel):
    """Comprehensive quality report for the entire pipeline.

    Attributes:
        project_name: Name of the project/object
        class_id: Class ID of the object
        stage_summaries: Quality summaries for each stage
        overall_status: Overall quality status (pass, warn, fail)
        overall_reasons: Aggregated reasons for the overall status
        suggestions: List of improvement suggestions
        available_stages: List of stages with available metrics
        missing_stages: List of stages with missing metrics
    """

    project_name: str
    class_id: int
    stage_summaries: list[StageQualitySummary]
    overall_status: str  # "pass", "warn", "fail"
    overall_reasons: list[str] = Field(default_factory=list)
    suggestions: list[str] = Field(default_factory=list)
    available_stages: list[str] = Field(default_factory=list)
    missing_stages: list[str] = Field(default_factory=list)

    model_config = {"frozen": True}
